apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-kube
  name: hello-kube
spec:
  selector:
    matchLabels:
      app: hello-kube
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - image: minikube/hello-kube:1.0
        imagePullPolicy: Never
        name: hello-kube
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
